name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run a CI
      run: npm ci
    - name: Install package
      run: npm install react
    - name: build
      run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.key}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist
